version: '3.5' # docker-compose version
services:
  config-service:
    container_name: config-service # name of the service
    build: config-service # way to the Dockerfile. The file is located in the "config-service" package
    ports:
      - 8001:8001 # open port

  registry:
    container_name: registry
    restart: always # restarting service
    build: registry
    ports:
      - 8761:8761
    depends_on:
      - config-service # start after "config-service"

  gateway:
    container_name: gateway
    restart: always
    build: gateway
    ports:
      - 8989:8989
    depends_on: # start after "config-service" and "registry"
      - config-service
      - registry

  account-service:
    restart: on-failure
    container_name: account-service
    build: account-service
    ports:
      - 8081:8081
    depends_on:
      - config-service
      - registry

  bill-service:
    restart: on-failure
    container_name: bill-service
    build: bill-service
    ports:
      - 8082:8082
    depends_on:
      - config-service
      - registry

  deposit-service:
    restart: on-failure
    container_name: deposit-service
    build: deposit-service
    ports:
      - 9090:9090
    depends_on:
      - config-service
      - registry

  notification-service:
    restart: on-failure
    container_name: notification-service
    build: notification-service
    depends_on:
      - config-service
      - registry

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: rabbitmq
    labels:
      NAME: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - config-service
      - registry
      - account-service