spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services # declaring the location where other configuration files will be located
  profiles:
    active: native # To use the native profile
  security:
    user: # name and  password to get access to the server
      password: admin
      name: user

server: # server and port to find common config service and get own settings (in all other services this port will be declared in "bootstrap.yml")
  port: 8001